name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup build environment
        uses: ./.github/actions/setup-gradle
        
      - name: Build
        run: ./gradlew build
        
      - name: Run tests
        run: ./gradlew test
        
      - name: Publish snapshot to Maven Central
        uses: ./.github/actions/publish-maven-central
        with:
          namespace: org.berrycrush
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
