name: PR

on:
  pull_request:
    branches: ['*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup build environment
        uses: ./.github/actions/setup-gradle
        
      - name: Build
        run: ./gradlew build
        
      - name: Run tests
        run: ./gradlew test
